## Optimizing the Python Code for Big Data 
Balancing Coding Complexity against Computational Complexity 

    
    AUTHOR: Dr. Roy Jafari 

# Chapter 4: Taking Advantage of Vectorization and Broadcasting (V&B) 

## Challenge 4: Matrix Multiplication or Loops?

Matrix multiplication is not used very often in everyday data preparation, however, it can be used time and again in the optimization sphere of machine learning. So in this challenge, the task we will focus on is a Quadratic Assignment Problem (QAP). 

QAP is an optimization problem, and we will see how the knowledge and experience of using matrix multiplication can help our big data task.

First, let us understand the QAP problem.

### Quadratic Assignment Problem (QAP)

In QAP, we have n machines and n locations. We denote *w_ij* as the flow between machine *i* and machine *j*, and the *n×n* matrix *W* as the flow matrix that shows the flow between every n machine. We notate *d_lk* as the distance between location *l* and location *k*, and the *n×n* matrix *D* as the distance matrix that shows the distance between every n location. The problem is to assign the *n* machines to the *n* locations such that the distance traveled between the machines is minimized after the assignment.

To solve QAP, the problem is encoded in a mathematical model. In the model, we define the decision variable *x_ik* as a binary variable whose value is 1 if the machine i is assigned to location *k*, and otherwise zero.

With this decision variable, we can put forth the following as the objective function of the mathematical model.

$Z =  \sum \limits _{i=1} ^{n} \sum \limits _{j=1} ^{n} w_{ij}d_{f(i)f(j)} $

In this formulation *f(i)* is the location where machine *i* is assigned and can be calculated using the following formula.

$f(i)=  \sum \limits _{k=1} ^{n} k x_{ik}$

Alternatively, the objective function of the QAP can be calculated using the following matrix multiplication.

$Z=trace(WXDX^T)$

In the preceding formula, *X* is an *n×n* matrix whose values are QAP’s decision variables *x_ik*. We had also defined *W* and *D*, previously.

Now, that we know about the QAP problem, let us roll up our sleeves and get into a more hands-on mode.


Before we get into the steps that you’d be taking let me share the good news with you: during this learn-by-doing opportunity, you will get to learn a bit about **Genetic Algorithms (GA)** as well. I am glad you are even more pumped now, so let’s get going. 


1.	Visit this webpage: https://coral.ise.lehigh.edu/data-sets/qaplib/qaplib-problem-instances-and-solutions. The page is called QAPLIB and has various examples of how the QAP problem be applied to the various aspects of business and industry. Please makes sure to scroll down to get to the sample data. For instance, when you scroll down about %25 of the page you will see **A.N. Elshafei**. Read the way this scholar took advantage of the QAP. Answer the following question, what is the problem they are solving? How does QAP contribute to this problem?

**Answer**:

This particular case study is about finding the best locations of various medical facilities given the usual movements of patients and staff between them. The goal is to assign the medical facilities in such way that the needed movements of patients and medical professionals will be minimized. 

QAP problem solves essentially the same problem. In QAP we talk about machines, but here we have medical facilities. In QAP products and raw materials will move between the machines, in here patients and medical staff move. Therefore, we can simply use QAP to model and solve this problem.

2.	On the same webpage, click on the problem instance *Els19*. The page that opens reveals the parameters of a QAP problem. The number *19*, in the beginning, is *n*, the first matrix is *D*, and the second matrix is *W* of the QAP problem. Introduce these three parameters to your computer python environment as *n*, *D*, and *W*. You may copy, and format the matrices, or you may find the chunks of codes that are prepared for you to copy, paste and run in the GitHub Repository of the book. Navigate to ch9 and then the *Chapter9.ipynb* file.

In [1]:
import numpy as np
import pandas as pd
n = 19

**Answer**:

In [2]:
W = np.array([
    [0 ,12,36,28,52,44,110,126,94, 63,130,102, 65,98,132,132,126,120,126],
    [12,0 ,24,75,82,75,108, 70,124, 86,93,106, 58,124,161,161,70 ,64, 70],
    [36,24,0 ,47 ,71 ,47 ,110,73,126,71, 95,110, 46,127,163,163,73,67,73],
    [28,75,47,0, 42,34,148,111,160, 52,94,148,49,117,104,109,111,105,111],
    [52,82,71,42,0 ,42,125,136,102,22,73,125, 32, 94,130,130,136,130,136],
    [44,75,47,34,42,0,148,111,162, 52, 96,148,49,117,152,152,111,105,111],
    [110,108,110,148,125,148,0 ,46,46 ,136,47,30,108,51,79,79,46, 47, 41],
    [126,70,73,111,136,111,46,0 ,69,141,63 ,46,119,68,121,121,27, 24, 36],
    [94,124,126,160,102,162,46 ,69,0 ,102,34 ,45 ,84 ,23 ,80,80,69,64,51],
    [63,86,71,52,22,52,136,141,102,0 ,64,118,29 ,95 ,131,131,141,135,141],
    [130,93 ,95,94,73,96,47 ,63 ,34,64,0 ,47 ,56 ,54 ,94 ,94 ,63 ,46 ,24],
    [102,106,110,148,125,148,30 ,46 ,45,118,47,0 ,100,51 ,89,89,46,40,36],
    [65,58,46,49 ,32 ,49,108,119,84,29,56,100,0 ,77 ,113,113,119,113,119],
    [98,124,127,117,94 ,117,51 ,68,23,95,54 ,51,77,0 ,79 ,79 ,68 ,62 ,51],
    [132,161,163,104,130,152,79,121,80,131,94,89,113,79,0,10,113,107,119],
    [132,161,163,109,130,152,79,121,80,131,94,89,113,79,10,0,113,107,119],
    [126,70,73,111,136,111,46, 27,69,141, 63, 46,119,68,113,113,0 ,6 ,24],
    [120,64,67,105,130,105,47, 24,64,135,46, 40,113, 62,107,107, 6,0 ,12],
    [126,70,73,111,136,111,41,36,51,141,24, 36,119, 51,119,119, 24, 12,0]
])

In [3]:
D = np.array([
    [0,76687,0,415,545,819,135,1368,819,5630,0,3432,9082,1503,0,0,13732,1368,1783],
    [76687, 0,40951,4118,5767,2055,1917,2746,1097,5712, 0, 0,0,268,0,1373,268,0,0],
    [0,40951, 0,3848,2524,3213,2072,4225,566, 0, 0,404,9372,0,972, 0,13538,1368,0],
    [415,4118,3848,  0,256,  0,  0,  0,  0,829,128,  0,  0,  0,  0,  0,  0,  0, 0],
    [545,5767,2524,256,  0,  0,  0,  0, 47,1655,287,  0, 42,  0,  0,  0,226, 0, 0],
    [819,2055,3213,  0,  0,  0,  0,  0,  0,926,161,  0,  0,  0,  0,  0,  0,  0, 0],
    [135,1917,2072,  0,  0,  0,  0,  0,196,1538,196, 0,  0,  0,  0,  0,  0,  0, 0],
    [1368,2746,4225, 0,  0,  0,  0,  0,  0,  0,301,  0,  0,  0,  0,  0,  0,  0, 0],
    [819,1097,566,   0, 47,  0,196,  0,  0,1954,418, 0,  0,  0,  0,  0,  0,  0, 0],
    [5630,5712,  0,829,1655,926,1538,  0,1954,  0,  0,282,0, 0,  0,  0,  0,  0, 0],
    [0,  0,  0,128,287,161, 196, 301, 418,  0,  0,1686,  0,  0,  0,  0, 226, 0, 0],
    [3432,  0,404,  0,  0,  0,  0,  0,  0,282,1686,  0,  0,  0,  0,  0,  0,  0, 0],
    [9082,  0,9372,  0, 42, 0,  0,  0,  0,  0,  0,   0,  0,  0,  0,  0,  0,  0, 0],
    [1503,268,  0,  0,  0,  0,  0,  0,  0,  0,  0,   0,  0,  0,  0,  0,  0,  0, 0],
    [0,  0, 972, 0,  0,  0,  0,  0,  0,  0,  0,  0,   0,  0,  0,99999,   0,  0, 0],
    [0,1373,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,99999,  0,   0,  0, 0],
    [13732,268,13538,0,226,  0,  0,  0,  0,  0,226,  0,  0,  0,  0,  0,  0,  0, 0],
    [1368,  0,1368,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 0],
    [1783,  0,  0,   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 0]
])

3.	The webpage also gives the optimal solution for the problem as well. Try to locate it on the page, and the optimal solution is given as the following sequence of numbers: 

**(9,10,7,18,14,19,13,17,6,11,4,5,12,8,15,16,1,2,3)**

This means in the optimal solution to the problem hospital facility 9 should be located at location 1, hospital facility 10 should be located at location 2, and so on. 

Now, pay attention to the following code. The code randomly generates a possible solution to the problem. The code uses the `numpy.random.permuation()` function. Run the code, a few times and describe what the function does.

**Answer**:

In [4]:
np.random.permutation(n)

array([18,  3,  6, 10, 16, 17, 15,  4, 14, 13,  8,  9,  1,  7,  5, 12, 11,
        2,  0])

The function randomly reorder all the numbers between 0 to 18. That is called the permutation of 19. 

4.	When we run the code in the preceding code, what is the probability that we chance upon the optimal solution? The correct answer is *8.2e-18*, but try to find it yourself. 

**Answer**:

The answer is $\frac{1}{19!}$ and the following chunk of code computes it.

In [5]:
import math
1/math.factorial(n)

8.22063524662433e-18

5.	The number of possible solutions for this problem is *19!* which is *121645100408832000*. Every time we run np. `random.permutation(n)`, we randomly get one of these possible solutions. That is a very convenient way of finding a feasible solution to an optimization problem. 

In Genetic Algorithm, we call each of these sequences of numbers a chromosome. We have different types of chromosomes, this specific one is called permutation encoding. 

Each chromosome is a special encoding of a possible solution to the problem. Each chromosome also has a matrix representation. The following code creates the function `get_matrix()` that outputs the matrix representation of the chromosome.

```
def get_matrix(choro):
    n = len(choro)
    X = np.zeros((n,n))
    X[np.arange(n),choro] = np.ones(n)
    return X.astype(int)
```

For example, run the following code that gets the matrix representation of the optimal solution chromosome of the problem. 

```
opt_seq = (9,10,7,18,14,19,13,17,6,11,4,5,12,8,15,16,1,2,3)
opt_choro = np.array(opt_seq)-1
X = get_matrix(opt_choro)
print(X)
```

Before running the code, let us go over the reason we had to take one away in the second line of the code. The reason is that python and numpy indexing starts from 0, but the indexing of chromosomes presented on QAPLIB starts from 1. To make sure that our codes will not run into errors we have to take one away so the indexing of the chromosome also starts from zero. 
Now run the code, and study its output. Check a few *x_ik* that you’d expect to be one. For instance, *x_08* must be 1, because as we established in the optimal solution to the problem hospital facility 9 should be located at location 1.

**Answer**:

In [6]:
def get_matrix(choro):
    n = len(choro)
    X = np.zeros((n,n))
    X[np.arange(n),choro] = np.ones(n)
    return X.astype(int)

In [7]:
opt_seq = (9,10,7,18,14,19,13,17,6,11,4,5,12,8,15,16,1,2,3)
opt_choro = np.array(opt_seq)-1
X = get_matrix(opt_choro)
print(X)

[[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


6.	In this step, we will create a function that calculates the objective function, and we will test it.

First, we need to define *f(i)* which we defined, under the subchapter *Quadratic Assignment Problem (QAP)*, as a function that gives the location where machine i is assigned. The function `f()` takes both `i` and `X`; in this function, `i` is the facility that we want to know its location in the matrix-represented solution `X`.

```
def f(i,m):
    out= 0 
    for k in range(n):
        out += k*m[i,k]
    return int(out)
```

Now, we can use `f()` to create the objective function `Z_loop()` as the following. The reason we are adding `_loop` to the function name is that we will be creating `Z_vb()` later in the challenge.
```
def Z_loop(X):
    Z,n = 0,len(X)
    for i in range(n):
        for j in range(n):
            Z += W[i,j]*D[f(i,X),f(j,X)]
    return Z
```
Now that we have a function that can calculate objective function, let’s give it a try and test it out. The following code calculates the objective function for the optimal solution from the QAPLIB, based on the source the answer should be 17212548. Run the following code, and confirm that our function is finding the right answer. 
```
opt_seq = (9,10,7,18,14,19,13,17,6,11,4,5,12,8,15,16,1,2,3)
opt_choro = np.array(opt_seq)-1
opt_X = get_matrix(opt_choro)
print(Z_loop(opt_X))
```

**Answer**:

In [8]:
def f(i,m):
    out= 0 
    for k in range(n):
        out += k*m[i,k]
    return int(out)

In [9]:
def Z_loop(X):
    Z,n = 0,len(X)
    for i in range(n):
        for j in range(n):
            Z += W[i,j]*D[f(i,X),f(j,X)]
    return Z

In [10]:
opt_seq = (9,10,7,18,14,19,13,17,6,11,4,5,12,8,15,16,1,2,3)
opt_choro = np.array(opt_seq)-1
opt_X = get_matrix(opt_choro)
print(Z_loop(opt_X))

17212548


The function `Z_loop()` does find the correct answer.

7.	In this step, we will create the function `Z_vb()` that uses matrix multiplication to find the value of the objective function for a matrix-represented solution.

```
def z_vb(X):
    return np.trace(W@X@D@X.T)
```

After defining the function, run `print(z_vb(opt_X))` and confirm that both `z_vb()` and `z_loop()` reach the same correct value. 


**Answer**:

In [11]:
def z_vb(X):
    return np.trace(W@X@D@X.T)

In [12]:
print(z_vb(opt_X))

17212548


The function `Z_vb()` does find the correct answer.

8.	Study the following code, explain what it does, run it, and finally use its output to answer the following question. 
What is a brute-force method?

```
import time
functions = {'loop':Z_loop,'vb':z_vb}
n_repeat = 1000
for method,Z in functions.items():
    t0 = time.time()
    for _ in range(n_repeat):
        Z(opt_X)
    ave_runtime = (time.time()-t0)/n_repeat
    print(f'{method} average runtime: {ave_runtime:.6f}')
```

If we were to use the brute-force method to find the optimal solution to the problem, how long it would take if we were using `z_loop()` vs. `z_vb()`?

You will see that even though the `Z_vb()` will be 122 times faster, however, finding the solution using the brute-force approach is not possible even by using `Z_vb()`.

That’s where an approach such as Genetic Algorithm (GA) comes into the picture. Before, continuing with our hands-on learning, let’s skip a beat and learn a bit about GA first.

**Answer**:

In [13]:
import time
functions = {'loop':Z_loop,'vb':z_vb}
n_repeat = 1000
for method,Z in functions.items():
    t0 = time.time()
    for _ in range(n_repeat):
        Z(opt_X)
    ave_runtime = (time.time()-t0)/n_repeat
    print(f'{method} average runtime: {ave_runtime:.6f}')

loop average runtime: 0.004333
vb average runtime: 0.000032


In [14]:
f'The number of years the brute-force will take when we use Z_loop() will be {0.006858*math.factorial(n)/60/60/24/365}.'

'The number of years the brute-force will take when we use Z_loop() will be 26453643.41082477.'

In [15]:
f'The number of years the brute-force will take when we use Z_vb() will be {0.000051*math.factorial(n)/60/60/24/365}.'

'The number of years the brute-force will take when we use Z_vb() will be 196724.38232021916.'

In [16]:
f'Z_loop() takes {0.006858/0.000051} times than Z_vb().'

'Z_loop() takes 134.47058823529412 times than Z_vb().'

### Genetic Algorithm (GA)

GA is similar to the brute-force approach as it also relies on trying different possible solutions to find a better solution(s). It is also different as GA does not have to use all of the possible solutions to terminate. It uses a smart and unique way to put itself on the path of improvement. GA starts with a population of random chromosomes, let’s say 100 chromosomes. These possible solutions to the problem are tired and are ranked based on their goodness. GA uses the current population to evolve into the next population, and the better chromosomes are more likely to have a role in evolution. This evolution happens multiple times, let’s say 1000 times. That’s a genetic algorithm in a nutshell; the only part we need to discuss is how the better chromosomes are selected to contribute to evolution and how they do contribute.

We will first talk about the types of contributions. There are three ways that a chromosome can have a role in generating the next population of chromosomes. These are elitism, crossover, and mutation. We will go over these, one by one. 

#### Eliticims
This is the simplest way a chromosome can contribute to the generation of the next population of chromosomes. When a handful of chromosomes are selected to be a part of the next population without any change, that is what literature calls elitism. Simply put, when a chromosome is selected as an elite of its population it will get the chance to carry over to the next population.
Next, we will talk about the crossover.

#### Crossover
In this way, two chromosomes get to co-contribute to the next population. Another simple way to think of crossover is to imagine the chromosomes getting married and having two children. The way they contribute to the next population is by having their children be included in the next population. Depending on the type of chromosomes there are various ways of marrying two chromosomes. The most famous types of chromosomes are binary encoding, permutation encoding, and tree encoding. 
As the problem we are solving here engages permutation encoding, let us go over the applicable crossover for permutation encoding, which is called **Ordered Crossover**.

The ordered crossover of two chromosomes generates two offspring. Each offspring gets half of its cells directly from a parent, the rest are filled from the second parent based on the order of those indices in the chromosome of the second parent. I am sure this hasn’t made sense yet, and I am sure it will once we go over the following example.

The following figure shows an example of an ordered crossover. We can see each offspring is influenced by both parents. There are two types of influences: direct, and order. The cells that are randomly picked for direct influence are exactly copied in the offspring. Then the cells that are remaining will be filled using the order influence from the other parent. For instance, in the case of offspring 1, the cells that are marked with 10, 2, 4, 8, and 6 are the result of the direct influence of parent 1; once those are filled, 5 empty cells remain, and the numbers 7, 3, 1, 9 and 5 have not been used yet. The order of these numbers in parent 2 is 1, 7, 3, 9 5, and that’s why the empty cells in offspring 1 are filled with these numbers and in that order. The same logic applies to offspring 2, however, it takes its direct influence from parent 2, and its order influence from parent 1.
 
 
![Figure 9.4 – Example of ordered crossover](ordered_crossover.png)

We will implement the code to perform ordered crossover later on in this challenge. Now, let’s see the last way a chromosome can play a role in the evolution of the next population; next, we will go over mutation. 

#### Mutation

When a chromosome undergoes mutation, a small change is applied to its chromosome. Again, the implementation of mutation will look different based on the type of chromosome. As in this challenge, we have permutation-encoding chromosomes we will see an example of this type of chromosome mutation.

Assume the following sequence of numbers is a permutation-encoding chromosome. 

**(9, 3, 1, 5, 10, 2, 4, 8, 6, 7)**.

When this chromosome undergoes a mutation, it could look something like this. We randomly select two indexes from 0 to 9; let’s say we happen upon 2 and 5. Then, we switch the numbers residing in those indices. For instance, the preceding chromosome when the indices 2 and 5 are chosen will be transformed into the following. Don’t forget we are starting our indexing from zero.

**(9, 3, 2, 5, 10, 1, 4, 8, 6, 7)**.

Next, let us briefly talk about how we go about randomly selecting chromosomes that will put GA on the path of improvement.

#### Random Selection
For every way we discussed that chromosomes in the current population can contribute to the next population, we need a methodology to choose which chromosomes will get to contribute. There can be various methods to go about this, however, the simplest and most effective one is called **Roulette Wheel Selection (RWS)** in the literature. 

I think the name is kind of confusing because it gives the impression that all the chromosomes have an equal chance of being selected, however, that’s not the case. Under RWS, chromosomes that have better goodness will have more chance of being selected. Essentially, RWS calculates a probability for each chromosome in the population and the better chromosomes will have a higher probability of being selected.

In this challenge, we will implement RWS, and you will see how those probabilities are calculated. I promise it is very easy and intuitive.

Now that we have a better understanding of what is GA. It is time that we get back to our hands-on learning steps and implement the Genetic algorithm on the problem we were trying to solve. 

### Hands-on Learning Continues
We will pick up our steps from where we left them. We completed step eight and now step nine.

9.	The following code creates the python class of objects chromosome. As we learned under GA, each chromosome is essentially a solution to the problem. Study the code. Especially pay attention to the usages of the functions `get_matrix()` and `z_vb()` that we developed earlier. Also, pay attention to the reserved function names __init__() and __repr__().

**Answer**:

In [17]:
class chromosome(object):
    def __init__(self,perm = [],n=19):
        self.n = n
        if perm:
            self.perm = np.array(perm)
        else:
            self.perm = np.random.permutation(self.n)

            
        self.X = get_matrix(self.perm)
        self.obj = z_vb(self.X)
        
    def __repr__(self):
        rep = f'''permutation:{self.perm}
        Objective value = {self.obj}'''
        return rep

10.	The following code creates one object of the class `chromosome` that we just created and also prints it. Run the code a few times and describe your observations.

**Answer**:

In [18]:
c1 = chromosome(n=19)
print(c1)

permutation:[ 5 11 16  0  2 10  6  1 12 18  9 15  8 13  7  4 14  3 17]
        Objective value = 58771244


11.	Next, we create a second python class of objects. This one is called `population` and its only properties are `n_members`, and `n_cells`. The former variable is the number of chromosome objects that the population has; whereas, the latter is the number of cells that each chromosome object has. Study and run its definition as the following code. 

**Answer**:

In [19]:
class population(object):
    def __init__(self,n_cells=10,n_members=100):
        self.n_pop = n_members     
        self.members = [
            chromosome(n=n_cells) for i in range(100)]
        self.probs = None
        self.best = None

12.	Run the following code to create a `population` of 100 `chromosome` objects with 19 cells, and then print out its first member. Study and run the following code. 

**Answer**:

In [20]:
pop = population(n_cells=19)
print(pop.members[0])

permutation:[ 3 10 13 14  9 12  7  2  4  1  0  5 17  6  8 11 15 18 16]
        Objective value = 61582674


13.	Pay attention to the definition of `population` in step 11. Each object of `population` has two more properties that we have not completed yet, and they are just `None` for now. The first one is probs; which is short for probabilities. The second one is best which will hold the best `chromosome` in each object of the `population`.

The following code creates the function `get_probs()` which takes in a population and returns the probability of its members being selected.
```
def get_probs(population):
    work_df = pd.DataFrame(
        {'obj': [chro.obj for chro in population]}
    )
    work_df['normalized'] = (
        (work_df.obj - work_df.obj.min())
        /
        (work_df.obj.max() - work_df.obj.min())
    )
    work_df['score'] = 1 - work_df.normalized
    total_score = work_df.score.sum()
    work_df['prob'] = work_df.score/total_score
    work_df = work_df.sort_values('prob',ascending=False)
    work_df['cumalative'] = work_df.prob.cumsum()
    return work_df[['prob','cumalative']]
```
After creating the function, running `get_probs(pop.members)` will use it to calculate the probability of selection for each of the chromosomes in `pop`. 

**Answer**:

In [21]:
def get_probs(population):
    work_df = pd.DataFrame(
        {'obj': [chro.obj for chro in population]}
    )
    work_df['normalized'] = (
        (work_df.obj - work_df.obj.min())
        /
        (work_df.obj.max() - work_df.obj.min())
    )
    work_df['score'] = 1 - work_df.normalized
    total_score = work_df.score.sum()
    work_df['prob'] = work_df.score/total_score
    work_df = work_df.sort_values('prob',ascending=False)
    work_df['cumalative'] = work_df.prob.cumsum()
    return work_df[['prob','cumalative']]

In [22]:
get_probs(pop.members)

prob  cumalative
75  0.020128    0.020128
23  0.018949    0.039077
36  0.018405    0.057482
64  0.018239    0.075721
47  0.017590    0.093312
..       ...         ...
51  0.003834    0.992071
12  0.003566    0.995638
10  0.003137    0.998775
17  0.001225    1.000000
97  0.000000    1.000000

[100 rows x 2 columns]

14.	Now that we have the function `get_probs()` working for us, let us complete the definition of the class of objects population. The following code is the complete version of populaiton. 

```
class population(object):
    def __init__(self,n_cells=19,n_members=100):
        self.n_pop = n_members     
        self.members = [
            chromosome(n=n_cells) for i in range(100)]        
        self.probs = get_probs(self.members)
        self.best = self.members[self.probs.iloc[0].name]
```
Pay attention, how the code uses the calculated probablities to also find the best chromosome out of all the members. Now if you run the following code, you will have a populaiton and for all of its members we have a probablity value, and also we know what is the best chromosome among all members. Run the following code to give this a try.
```
pop = population()
print(pop.best)
```

**Answer**:

In [23]:
class population(object):
    def __init__(self,n_cells=19,n_members=100):
        self.n_pop = n_members     
        self.members = [
            chromosome(n=n_cells) for i in range(n_members)]
        
        self.probs = get_probs(self.members)
        self.best = self.members[self.probs.iloc[0].name]

In [24]:
pop = population()
print(pop.best)

permutation:[18 16 13 12  3 10  7  4  2  8  1  0 17  9 15 14  6  5 11]
        Objective value = 34116334


15.	One last time, we will improve the definition of the class `population`. We will add two capabilities. First, at its current state, the `population` can only create new populations randomly, but what if we need to create a population using members of chromosomes that we already have? This will be important when we want to create a future population from an existing one with some changes. 

Secondly, the new definition also has a function `pick_members()` that can randomly select members from the population using the probabilities we calculated in the previous step. Pay attention that `pick_members()` takes in n as the number of random members you’d like to pick.

Study and then run the following code to create the improved population class.

```
class population(object):
    def __init__(self,members = [],
                 n_members=100, n_cells=19):               
        if members:
            self.n_cells = members[0].n
            self.n_pop = len(members)
            self.members = members
        else:
            self.n_cells = n_cells
            self.n_pop = n_members
            self.members = [chromosome(n=self.n_cells)
                            for i in range(self.n_pop)]         
        self.probs = get_probs(self.members)
        self.best = self.members[self.probs.iloc[0].name]
    def pick_members(self, n=1):
        members = []
        for random_num in np.random.random(n):
            BM = (self.probs.cumalative>=random_num)
            index = self.probs[BM].iloc[0].name
            members.append(self.members[index])
        return members    
```

Once you introduced the final version of population class to your local python environment, run the following code to give the new function `pick_members()` a try. Run it a few times to experience the randomness.
```
one_chro = pop.pick_members(n=1)[0]
print(one_chro)
```

**Answer**:

In [25]:
class population(object):
    def __init__(self,members = [],
                 n_members=100, n_cells=19):               
        if members:
            self.n_cells = members[0].n
            self.n_pop = len(members)
            self.members = members
        else:
            self.n_cells = n_cells
            self.n_pop = n_members
            self.members = [chromosome(n=self.n_cells)
                            for i in range(self.n_pop)]         
        self.probs = get_probs(self.members)
        self.best = self.members[self.probs.iloc[0].name]
    def pick_members(self, n=1):
        members = []
        for random_num in np.random.random(n):
            BM = (self.probs.cumalative>=random_num)
            index = self.probs[BM].iloc[0].name
            members.append(self.members[index])
        return members    

In [26]:
pop = population()

In [27]:
one_chro = pop.pick_members(n=1)[0]
print(one_chro)

permutation:[13  6 16  3  9  2 12 10  5 15 14  4 17  0  7 11 18  8  1]
        Objective value = 52107324


16.	The following code creates the function `mutate()` to perform the mutation operation that we discussed earlier. In this function, the input severity, which has a default value of 0.25, is the ratio of the cells that will be affected. As the number of cells of our chromosomes in this problem is 19, when the severity value is 0.25, the `n_changes` will be round(0.25*19) which is 5.

```
def mutate(chro,severity=0.25):
    n_changes = int(np.round(severity*chro.n))
    new_chro = chro.perm.copy()
    for _ in range(n_changes):
        random_cells = np.random.randint(0,n,2)
        if random_cells[0] == random_cells[1]:
            continue
        keep = new_chro[random_cells[0]]
        new_chro[random_cells[0]
                ] = new_chro[random_cells[1]]
        new_chro[random_cells[1]] = keep
    return chromosome(new_chro.tolist())
```

After creating the function, run the following code to test it and experience the changes the function inflicts on the inputted chromosome. Run it a few times to also experience the randomness that is involved.
```
one_chro =pop.pick_members(n=1)[0]
print(one_chro)
print(mutate(one_chro))
```


**Answer**:

In [28]:
def mutate(chro,severity=0.25):
    n_changes = int(np.round(severity*chro.n))
    new_chro = chro.perm.copy()
    for _ in range(n_changes):
        random_cells = np.random.randint(0,n,2)
        if random_cells[0] == random_cells[1]:
            continue
        keep = new_chro[random_cells[0]]
        new_chro[random_cells[0]
                ] = new_chro[random_cells[1]]
        new_chro[random_cells[1]] = keep
    return chromosome(new_chro.tolist())

In [29]:
one_chro =pop.pick_members(n=1)[0]
print(one_chro)
print(mutate(one_chro))

permutation:[18 17 14  6  0  4  9  8 12  2  5 13  7 10  3  1 11 15 16]
        Objective value = 68800120
permutation:[18  1 13  6 17  4  9  8 15  2  5 14  7 10 12  0 11  3 16]
        Objective value = 63269932


17.	The following code is the definition of the function `cross_over()` which takes in two chromosomes and applies ordered crossover on them as explained earlier. Run the following code to define the function in your local python environment.

```
def cross_over(chro1,chro2):
    n_cells = chro1.n
    n_change = int(np.round(n_cells/2))
    randm_index = np.random.permutation(n_cells)
    stay_chro1 = randm_index[:n_change]
    stay_chro2 = randm_index[n_change:]
    child1 = chro1.perm.copy()
    child2 = chro2.perm.copy()
    child1[stay_chro2] = -1
    child2[stay_chro1] = -1
    exist1 = [i for i in child1 if i!=-1]
    exist2 = [i for i in child2 if i!=-1]
    not_filled1 = chro1.perm[stay_chro2].tolist()
    not_filled2 = chro2.perm[stay_chro1].tolist()
    order1 = [i for i in chro2.perm if i in not_filled1]
    order2 = [i for i in chro1.perm if i in not_filled2]
    child1[sorted(stay_chro2)] = order1
    child2[sorted(stay_chro1)] = order2
    return (
        chromosome(perm=child1.tolist()),
        chromosome(perm=child2.tolist())
    )
```

After creating the function, run the following code to experience how the function will impact the inputted chromosomes. Try running it a few times and studying the printout to also experience all the randomness that is involved.
```
chros = pop.pick_members(n=2)
print(chros)
print(cross_over(chros[0],chros[1]))
```

**Answer**:

In [30]:
def cross_over(chro1,chro2):
    n_cells = chro1.n
    n_change = int(np.round(n_cells/2))
    randm_index = np.random.permutation(n_cells)
    stay_chro1 = randm_index[:n_change]
    stay_chro2 = randm_index[n_change:]
    child1 = chro1.perm.copy()
    child2 = chro2.perm.copy()
    child1[stay_chro2] = -1
    child2[stay_chro1] = -1
    exist1 = [i for i in child1 if i!=-1]
    exist2 = [i for i in child2 if i!=-1]
    not_filled1 = chro1.perm[stay_chro2].tolist()
    not_filled2 = chro2.perm[stay_chro1].tolist()
    order1 = [i for i in chro2.perm if i in not_filled1]
    order2 = [i for i in chro1.perm if i in not_filled2]
    child1[sorted(stay_chro2)] = order1
    child2[sorted(stay_chro1)] = order2
    return (
        chromosome(perm=child1.tolist()),
        chromosome(perm=child2.tolist())
    )

In [31]:
chros = pop.pick_members(n=2)
print(chros)
print(cross_over(chros[0],chros[1]))

[permutation:[ 3  8 13  4 11 15 18  0 17  5  2 10 12 14  7  1  9  6 16]
        Objective value = 68070716, permutation:[18 17  1  7 15 13  8  5 16 12 14  4 11  2  3  6  9  0 10]
        Objective value = 54285842]
(permutation:[18  8  1  7 15 13  4  0 17  5  2 11 12 14  3 10  9  6 16]
        Objective value = 53994580, permutation:[18 11  1  7 15 13  8  0 17  5  2  4 10 12  3  6 14  9 16]
        Objective value = 62247800)


18.	Finally, we are ready to run the main loop of GA algorithm. The following code uses a for-loop code for the GA’s evolution process. Running the code will randomly, but smartly (because of GA), create and test 10,000 different possible solutions, and will show you the best among them. Run the code and time how long it takes to run. If you’d like to see the best solution in each iteration of the GA’s main, make sure to uncomment `#print(pop.best)` before running the code.

```
n_pop =  100
n_elit = np.round(0.05*n_pop).astype(int)
n_new = np.round(0.1*n_pop).astype(int)
n_mutate = np.round(0.2*n_pop).astype(int)
n_cross = np.round(0.65*n_pop).astype(int)
pop = population(n_members=n_pop, n_cells=19)
for _ in range(100):
    next_pop = pop.pick_members(n_elit-1)
    next_pop.append(pop.best)
    next_pop.extend(
        [chromosome(n=19) for i in range(n_new)])
    for _ in range(n_mutate):
        next_pop.append(mutate(pop.pick_members()[0],
                               severity=0.5))
    for _ in range(n_cross//2+1):
        chros = pop.pick_members(2)
        next_pop.extend(
            cross_over(chros[0],chros[1]))
    while len(next_pop)>100:
        next_pop.pop()
    pop = population(members = next_pop)
    #print(pop.best)
print(pop.best)
```

**Answer**:

In [32]:
%%time
n_pop =  100
n_elit = np.round(0.05*n_pop).astype(int)
n_new = np.round(0.1*n_pop).astype(int)
n_mutate = np.round(0.2*n_pop).astype(int)
n_cross = np.round(0.65*n_pop).astype(int)
pop = population(n_members=n_pop, n_cells=19)

for _ in range(100):
    next_pop = pop.pick_members(n_elit-1)
    next_pop.append(pop.best)
    next_pop.extend(
        [chromosome(n=19) for i in range(n_new)])
    for _ in range(n_mutate):
        next_pop.append(mutate(pop.pick_members()[0],
                               severity=0.5))
    for _ in range(n_cross//2+1):
        chros = pop.pick_members(2)
        next_pop.extend(
            cross_over(chros[0],chros[1]))
    while len(next_pop)>100:
        next_pop.pop()
    pop = population(members = next_pop)
    #print(pop.best)
print(pop.best)

permutation:[ 4  8  9  6 18 13 16  2  5 11 10  3 17  7 15 14  1  0 12]
        Objective value = 20858590
Wall time: 3.63 s


The loop takes about a 3 and half seconds to complete.

19.	When I ran the above code on my computer the best solution found was **[15,14,7,6,18,13,16,4,8,17,9,12,5,3,11,10,2,0,1]** and its objective value was **20,876,894**. It took my computer **3.55** seconds to complete it. Pay attention as GA is a random algorithm you may get a completely different solution, maybe even better or worse. 

Even though we were not able to find the optimal solution whose objective value is 17,212,548, we are still doing much better than just a random search. It is very simple to confirm that GA is making a difference. Run the code in the previous step a few times, and note the range of best solutions you will find. After that, run the following code a few times, and again note the range of different best solutions you will find. Pay attention to the following code blindly generate 10,000 possible random solutions and test them.
```
pop = population(n_members=10000, n_cells=19)
pop.best
```
What is your conclusion?


**Answer**:

In [46]:
%%time
pop = population(n_members=10000, n_cells=19)
pop.best

Wall time: 551 ms


permutation:[15 14  8 11  4 10  9 13 12  6 18  2 16 17  3  5  7  0  1]
        Objective value = 27475244

The conclusion is with the same number of randomly testing out possible solutions GA directs the randomness toward finding better solutions than just blindly testing out random solutions.

20.	So far we were able to experience the positive impact of the Genetic Algorithm in this challenge, however, learning Genetic Algorithm is our second priority, in this challenge we want to learn about the impact of V&B, specifically the matrix multiplication. This can be done by a simple change in the definition of the class chromosome. In the following code you can see, `Z_vb()` has been replaced with `Z_loop()`. This change essentially forces python to use a looping paradigm instead of matrix multiplication to calculate the objective value for each possible solution.

```
class chromosome(object):
    def __init__(self,perm = [],n=19):
        self.n = n
        if perm:
            self.perm = np.array(perm)
        else:
            self.perm = np.random.permutation(self.n)
        self.X = get_matrix(self.perm)
        self.obj = Z_loop(self.X)
    def __repr__(self):
        rep = f'''permutation:{self.perm}
        Objective value = {self.obj}'''
        return rep
```

Run the preceding code, and then run the main GA loop in step 18. Note how long your code takes to run. What is your conclusion?


**Answer**:

In [47]:
class chromosome(object):
    def __init__(self,perm = [],n=19):
        self.n = n
        if perm:
            self.perm = np.array(perm)
        else:
            self.perm = np.random.permutation(self.n)
        self.X = get_matrix(self.perm)
        self.obj = Z_loop(self.X)
    def __repr__(self):
        rep = f'''permutation:{self.perm}
        Objective value = {self.obj}'''
        return rep

In [48]:
%%time
n_pop =  100
n_elit = np.round(0.05*n_pop).astype(int)
n_new = np.round(0.1*n_pop).astype(int)
n_mutate = np.round(0.2*n_pop).astype(int)
n_cross = np.round(0.65*n_pop).astype(int)
pop = population(n_members=n_pop, n_cells=19)

for _ in range(100):
    next_pop = pop.pick_members(n_elit-1)
    next_pop.append(pop.best)
    next_pop.extend(
        [chromosome(n=19) for i in range(n_new)])
    for _ in range(n_mutate):
        next_pop.append(mutate(pop.pick_members()[0],
                               severity=0.5))
    for _ in range(n_cross//2+1):
        chros = pop.pick_members(2)
        next_pop.extend(
            cross_over(chros[0],chros[1]))
    while len(next_pop)>100:
        next_pop.pop()
    pop = population(members = next_pop)
    #print(pop.best)
print(pop.best)

permutation:[13 18  8  6 11  7  3  5 16 17  0  2 10 12  9  4 14 15  1]
        Objective value = 24981292
Wall time: 46.1 s


The conclusion is that the very same analytic performance we got before took about 12 times more to run. This shows the extent to which we can gain performance improvement when we can take advantage of matrix multiplication.