# Zero To Hero Big Data Prepration
Taking Advantage of Cloud Technologies to Create Big Data Solutions
    
    AUTHOR: Dr. Roy Jafari 

# Chapter 3: Using the right data strucutres 

## Data Types vs. Data Structures
### What is a table?
### What is a dictionary?

In [30]:
questions = {'Q1':'What is your name?',
             'Q2':'What is your education level?',
             'Q3':'What is your address?'}
print(questions)

{'Q1': 'What is your name?', 'Q2': 'What is your education level?', 'Q3': 'What is your address?'}


### What is a linked list?

In [31]:
a_list = ['item1','item2','item3','item4']
print(a_list)

['item1', 'item2', 'item3', 'item4']


In [32]:
class ListNode(object):
    def __init__(self, val=None, next=None):
        self.val = val
        self.next = next

In [33]:
item1 = ListNode('item1')
item2 = ListNode('item2')
item3 = ListNode('item3')
item4 = ListNode('item4')

item1.next = item2
item2.next = item3
item3.next = item4

In [34]:
def print_linked_list_by_head(head):
    printout = ''
    node = head
    while node is not None:
        printout += f'{node.val} -> '
        node = node.next
    print(printout)

In [35]:
print_linked_list_by_head(item1)

item1 -> item2 -> item3 -> item4 -> 


### What is a tree?

In [46]:
class TreeNode(object):
    def __init__(self,val=None):
        self.val = val
        self.children = []

In [47]:
n1 = TreeNode(1)
n2 = TreeNode(2)
n3 = TreeNode(3)
n4 = TreeNode(4)
n5 = TreeNode(5)
n6 = TreeNode(6)
n7 = TreeNode(7)

n1.children.extend([n2,n3])
n2.children.extend([n4,n5,n6])
n3.children.append(n7)

In [50]:
def print_tree_from_root(root):
    
    print_order = []
    def get_print_order(root,l=0):
        if len(root.children) ==0:
            return (root.val,l)
        print_order.append((root.val,l))
        l +=1
        for child in root.children:
            print_order.append(get_print_order(child,l))
            
    get_print_order(root)
    
    
    for val,l in [tup for tup in print_order if tup]:
        print('___'*l + str(val))

In [51]:
print_tree_from_root(n1)

1
___2
______4
______5
______6
___3
______7


### What is a Graph?
#### List of Edges

In [11]:
import pandas as pd
class GraphLE(object):
    def __init__(self,n_nodes=None):
        self.edge_df = pd.DataFrame(
            columns = ['n1','n2','w']
        )
        self.n_nodes = n_nodes
    def add_edge(self,n1,n2,w=1):
        add_df = pd.DataFrame(
            {'n1': n1, 'n2': n2, 'w': w},
            index=[len(self.edge_df)]
        )
        self.edge_df = pd.concat([self.edge_df,add_df])
    def print_all_adj_list(self):
        print(self.edge_df)
    def get_edge_from(self,node):
        BM = self.edge_df.n1 == node
        return [(r.n1,r.n2,r.w) for i,r in 
               self.edge_df[BM].iterrows()]

In [12]:
le_graph = GraphLE(7)
edge_list = [(3,0,5),(3,1,2),(1,0,7),(0,2,1),(2,5,9),(6,2,3),(5,6,3),(5,1,2),(5,4,9),(4,1,3),(4,5,8)]
for n1,n2,w in edge_list:
    le_graph.add_edge(n1,n2,w)

In [13]:
le_graph.print_all_adj_list()

   n1 n2  w
0   3  0  5
1   3  1  2
2   1  0  7
3   0  2  1
4   2  5  9
5   6  2  3
6   5  6  3
7   5  1  2
8   5  4  9
9   4  1  3
10  4  5  8


In [14]:
print(le_graph.get_edge_from(5))

[(5, 6, 3), (5, 1, 2), (5, 4, 9)]


#### Adjecancy Matrix

In [15]:
import numpy as np
import pandas as pd
class GraphAM(object):
    def __init__(self,n_nodes):
        self.n_nodes = n_nodes
        self.adj_matrix = (
            np.zeros([n_nodes,n_nodes])
            .astype(int)
        )
    def add_edge(self,n1,n2,w=1):
        self.adj_matrix[n1,n2] = w
    def print_adj_matrix(self):
        print(self.adj_matrix)
    def get_edge_from(self,n1):
        return [(n1,n2,w) for n2,w in
                enumerate(self.adj_matrix[n1,:]) if w>0]

In [16]:
am_graph = GraphAM(7)
edge_list = [(3,0,5),(3,1,2),(1,0,7),(0,2,1),(2,5,9),(6,2,3),(5,6,3),(5,1,2),(5,4,9),(4,1,3),(4,5,8)]
for n1,n2,w in edge_list:
    am_graph.add_edge(n1,n2,w)

In [17]:
am_graph.print_adj_matrix()

[[0 0 1 0 0 0 0]
 [7 0 0 0 0 0 0]
 [0 0 0 0 0 9 0]
 [5 2 0 0 0 0 0]
 [0 3 0 0 0 8 0]
 [0 2 0 0 9 0 3]
 [0 0 3 0 0 0 0]]


In [18]:
print(am_graph.get_edge_from(5))

[(5, 1, 2), (5, 4, 9), (5, 6, 3)]


#### Adjecancy List

In [19]:
class GraphAL(object):
    def __init__(self,n_nodes):
        self.n_nodes = n_nodes
        self.adj_list = {
            node: list() for node in range(self.n_nodes)
        }
    def add_edge(self,n1,n2,w=1):
        (self
         .adj_list[n1]
         .append((n2,w))
        )
    def print_all_adj_list(self):
        for key in self.adj_list.keys():
            print(key,self.adj_list[key])
    def get_edge_from(self,n1):
        return [(n1,n2,w) for n2,w in self.adj_list[n1]]

In [20]:
al_graph = GraphAL(7)
edge_list = [(3,0,5),(3,1,2),(1,0,7),(0,2,1),(2,5,9),(6,2,3),(5,6,3),(5,1,2),(5,4,9),(4,1,3),(4,5,8)]
for n1,n2,w in edge_list:
    al_graph.add_edge(n1,n2,w)

In [21]:
al_graph.print_all_adj_list()

0 [(2, 1)]
1 [(0, 7)]
2 [(5, 9)]
3 [(0, 5), (1, 2)]
4 [(1, 3), (5, 8)]
5 [(6, 3), (1, 2), (4, 9)]
6 [(2, 3)]


In [22]:
print(al_graph.get_edge_from(5))

[(5, 6, 3), (5, 1, 2), (5, 4, 9)]


## Challenge 1: table or dictionary

In [1]:
import names
import numpy as np

f_names = [names.get_first_name() for i in range(5000)]
l_names = [names.get_last_name() for i in range(5000)]

fullnames = list(set([f'{fn} {ln}' for fn in f_names for ln in l_names]))
ages = np.random.randint(18,75,len(fullnames)).tolist()
married = np.random.choice(
    [True,False], len(fullnames)
).tolist()

In [2]:
fullnames.append('Roy Jafari')
ages.append(35)
married.append(True)

In [19]:
import pandas as pd
person_df = pd.DataFrame(
    {'Name':fullnames, 'Age':ages, 'Married':married}
)
print(person_df)

                        Name  Age  Married
0           Thaddeus Barbosa   60    False
1                Avis Maciel   31    False
2            Bradford Callen   33     True
3              Shannon Groce   42    False
4                 Titus Culp   69    False
...                      ...  ...      ...
3973476     Clifford Friddle   45     True
3973477     Odis Kirkpatrick   68     True
3973478            Gus Grigg   46     True
3973479  Francis Matuszewski   51     True
3973480           Roy Jafari   35     True

[3973481 rows x 3 columns]


In [25]:
person_dict = {fullnames[i]:(ages[i],married[i]) for i in range(len(ages))}
person_dict

{'Thaddeus Barbosa': (60, False),
 'Avis Maciel': (31, False),
 'Bradford Callen': (33, True),
 'Shannon Groce': (42, False),
 'Titus Culp': (69, False),
 'Terri Cepeda': (33, True),
 'Dovie Shones': (40, True),
 'Gertrude Payne': (22, False),
 'Hortense Mcgalliard': (65, False),
 'Max Jeffery': (41, False),
 'Eugene Mata': (64, False),
 'Nancy Corley': (61, False),
 'Virginia Reyes': (64, False),
 'Jeremy Sherman': (49, True),
 'Marguerite Sturgis': (31, True),
 'Jannet Stillson': (51, True),
 'Terra Eady': (74, False),
 'Thaddeus Aponte': (74, False),
 'Silas Mcgee': (20, True),
 'Wallace Sturgis': (47, False),
 'Melody Rios': (20, True),
 'Karen Bramlett': (53, True),
 'Violet Mcmackin': (54, False),
 'Virginia Lewis': (20, True),
 'Eloise Everson': (68, False),
 'Joann Stuart': (47, True),
 'Hollis Santoyo': (24, False),
 'Harry Minahan': (22, True),
 'Tamie Richner': (21, True),
 'Nicolas Wheeler': (62, False),
 'Eartha Whitt': (68, True),
 'Zachary Mahn': (64, True),
 'Ryan Lee':

In [5]:
import time

t0=time.time()
result = person_df[person_df.Name == 'Roy Jafari']
print(time.time()-t0,'(s)')
print(result)

1.071505069732666 (s)
               Name  Age  Married
3973480  Roy Jafari   35     True


In [8]:
t0=time.time()
result = person_dict['Roy Jafari']
print(time.time()-t0,'(s)')
print(result)

0.0 (s)
(35, True)


In [20]:
person_df = person_df.set_index('Name')
print(person_df)

                     Age  Married
Name                             
Thaddeus Barbosa      60    False
Avis Maciel           31    False
Bradford Callen       33     True
Shannon Groce         42    False
Titus Culp            69    False
...                  ...      ...
Clifford Friddle      45     True
Odis Kirkpatrick      68     True
Gus Grigg             46     True
Francis Matuszewski   51     True
Roy Jafari            35     True

[3973481 rows x 2 columns]


In [23]:
import time

t0=time.time()
result = person_df.loc['Roy Jafari']
print(time.time()-t0,'(s)')
print(result)

0.0010898113250732422 (s)
Age          35
Married    True
Name: Roy Jafari, dtype: object


## Challenge 2: lists or linked lists?

In [560]:
import numpy as np

a_list = np.random.randint(0,100,100000).tolist()

In [ ]:
class ListNode(object):
    def __init__(self, val=None, next=None):
        self.val = val
        self.next = next

In [561]:
node = ListNode()
dummy = node

for n in a_list:
    node.next = ListNode(n)
    node = node.next
    
head_linked_list = dummy.next

In [568]:
def print_linked_list_by_head(head):
    printout = ''
    node = head
    while node is not None:
        printout += f'{node.val} -> '
        node = node.next
    print(printout)

In [570]:
print(a_list)

[41, 31, 47, 73, 1, 3, 23, 53, 41, 83, 25, 51, 35, 61, 59, 93, 7, 15, 95, 45, 15, 83, 63, 23, 39, 79, 47, 93, 27, 75, 7, 31, 49, 13, 39, 1, 9, 93, 41, 71, 97, 25, 69, 85, 5, 97, 99, 43, 13, 91, 51, 47, 81, 15, 53, 29, 41, 17, 65, 63, 51, 53, 83, 35, 93, 95, 31, 57, 79, 19, 27, 33, 73, 29, 77, 27, 17, 93, 17, 89, 89, 33, 95, 35, 79, 95, 91, 67, 25, 41, 57, 19, 77, 23, 21, 13, 29, 19, 11, 41, 77, 39, 27, 57, 63, 3, 5, 9, 89, 73, 69, 39, 85, 19, 73, 87, 65, 75, 43, 25, 31, 51, 49, 89, 5, 99, 91, 61, 99, 27, 49, 91, 17, 79, 21, 27, 15, 15, 15, 89, 73, 85, 71, 61, 95, 5, 95, 69, 71, 37, 69, 37, 89, 55, 11, 73, 93, 45, 89, 57, 31, 31, 61, 33, 23, 59, 47, 37, 99, 81, 69, 23, 41, 83, 81, 35, 55, 91, 37, 63, 73, 63, 89, 31, 93, 83, 69, 67, 41, 5, 67, 17, 45, 7, 61, 75, 81, 85, 15, 27, 65, 23, 89, 57, 37, 79, 85, 69, 13, 77, 25, 87, 75, 47, 37, 55, 1, 59, 75, 61, 11, 75, 79, 69, 83, 33, 51, 69, 9, 31, 61, 29, 93, 53, 75, 3, 77, 97, 75, 7, 35, 9, 91, 47, 51, 75, 13, 89, 51, 89, 23, 53, 81, 53, 67

In [571]:
print_linked_list_by_head(head_linked_list)

41 -> 31 -> 47 -> 73 -> 1 -> 3 -> 23 -> 53 -> 41 -> 83 -> 25 -> 51 -> 35 -> 61 -> 59 -> 93 -> 7 -> 15 -> 95 -> 45 -> 15 -> 83 -> 63 -> 23 -> 39 -> 79 -> 47 -> 93 -> 27 -> 75 -> 7 -> 31 -> 49 -> 13 -> 39 -> 1 -> 9 -> 93 -> 41 -> 71 -> 97 -> 25 -> 69 -> 85 -> 5 -> 97 -> 99 -> 43 -> 13 -> 91 -> 51 -> 47 -> 81 -> 15 -> 53 -> 29 -> 41 -> 17 -> 65 -> 63 -> 51 -> 53 -> 83 -> 35 -> 93 -> 95 -> 31 -> 57 -> 79 -> 19 -> 27 -> 33 -> 73 -> 29 -> 77 -> 27 -> 17 -> 93 -> 17 -> 89 -> 89 -> 33 -> 95 -> 35 -> 79 -> 95 -> 91 -> 67 -> 25 -> 41 -> 57 -> 19 -> 77 -> 23 -> 21 -> 13 -> 29 -> 19 -> 11 -> 41 -> 77 -> 39 -> 27 -> 57 -> 63 -> 3 -> 5 -> 9 -> 89 -> 73 -> 69 -> 39 -> 85 -> 19 -> 73 -> 87 -> 65 -> 75 -> 43 -> 25 -> 31 -> 51 -> 49 -> 89 -> 5 -> 99 -> 91 -> 61 -> 99 -> 27 -> 49 -> 91 -> 17 -> 79 -> 21 -> 27 -> 15 -> 15 -> 15 -> 89 -> 73 -> 85 -> 71 -> 61 -> 95 -> 5 -> 95 -> 69 -> 71 -> 37 -> 69 -> 37 -> 89 -> 55 -> 11 -> 73 -> 93 -> 45 -> 89 -> 57 -> 31 -> 31 -> 61 -> 33 -> 23 -> 59 -> 47 -> 37 -> 99 -

In [564]:
import time

t0 = time.time()

i=0
while i<len(a_list):
    if a_list[i] % 2 ==0:
        a_list.pop(i)
    else:
        i+=1
        
print(time.time()-t0,'s')

7.001850128173828 s


In [565]:
t0 = time.time()

dummy = ListNode(1)
dummy.next = head_linked_list
node = dummy

previous = node
node = node.next

while node is not None:
    
    if node.val %2 ==0:
        previous.next = node.next
    else:
        previous = node
        
    node = node.next
head_linked_list = dummy.next

print(time.time()-t0,'s')

0.03555583953857422 s


In [566]:
print(a_list)

[41, 31, 47, 73, 1, 3, 23, 53, 41, 83, 25, 51, 35, 61, 59, 93, 7, 15, 95, 45, 15, 83, 63, 23, 39, 79, 47, 93, 27, 75, 7, 31, 49, 13, 39, 1, 9, 93, 41, 71, 97, 25, 69, 85, 5, 97, 99, 43, 13, 91, 51, 47, 81, 15, 53, 29, 41, 17, 65, 63, 51, 53, 83, 35, 93, 95, 31, 57, 79, 19, 27, 33, 73, 29, 77, 27, 17, 93, 17, 89, 89, 33, 95, 35, 79, 95, 91, 67, 25, 41, 57, 19, 77, 23, 21, 13, 29, 19, 11, 41, 77, 39, 27, 57, 63, 3, 5, 9, 89, 73, 69, 39, 85, 19, 73, 87, 65, 75, 43, 25, 31, 51, 49, 89, 5, 99, 91, 61, 99, 27, 49, 91, 17, 79, 21, 27, 15, 15, 15, 89, 73, 85, 71, 61, 95, 5, 95, 69, 71, 37, 69, 37, 89, 55, 11, 73, 93, 45, 89, 57, 31, 31, 61, 33, 23, 59, 47, 37, 99, 81, 69, 23, 41, 83, 81, 35, 55, 91, 37, 63, 73, 63, 89, 31, 93, 83, 69, 67, 41, 5, 67, 17, 45, 7, 61, 75, 81, 85, 15, 27, 65, 23, 89, 57, 37, 79, 85, 69, 13, 77, 25, 87, 75, 47, 37, 55, 1, 59, 75, 61, 11, 75, 79, 69, 83, 33, 51, 69, 9, 31, 61, 29, 93, 53, 75, 3, 77, 97, 75, 7, 35, 9, 91, 47, 51, 75, 13, 89, 51, 89, 23, 53, 81, 53, 67

In [567]:
print_linked_list_by_head(head_linked_list)

41 -> 31 -> 47 -> 73 -> 1 -> 3 -> 23 -> 53 -> 41 -> 83 -> 25 -> 51 -> 35 -> 61 -> 59 -> 93 -> 7 -> 15 -> 95 -> 45 -> 15 -> 83 -> 63 -> 23 -> 39 -> 79 -> 47 -> 93 -> 27 -> 75 -> 7 -> 31 -> 49 -> 13 -> 39 -> 1 -> 9 -> 93 -> 41 -> 71 -> 97 -> 25 -> 69 -> 85 -> 5 -> 97 -> 99 -> 43 -> 13 -> 91 -> 51 -> 47 -> 81 -> 15 -> 53 -> 29 -> 41 -> 17 -> 65 -> 63 -> 51 -> 53 -> 83 -> 35 -> 93 -> 95 -> 31 -> 57 -> 79 -> 19 -> 27 -> 33 -> 73 -> 29 -> 77 -> 27 -> 17 -> 93 -> 17 -> 89 -> 89 -> 33 -> 95 -> 35 -> 79 -> 95 -> 91 -> 67 -> 25 -> 41 -> 57 -> 19 -> 77 -> 23 -> 21 -> 13 -> 29 -> 19 -> 11 -> 41 -> 77 -> 39 -> 27 -> 57 -> 63 -> 3 -> 5 -> 9 -> 89 -> 73 -> 69 -> 39 -> 85 -> 19 -> 73 -> 87 -> 65 -> 75 -> 43 -> 25 -> 31 -> 51 -> 49 -> 89 -> 5 -> 99 -> 91 -> 61 -> 99 -> 27 -> 49 -> 91 -> 17 -> 79 -> 21 -> 27 -> 15 -> 15 -> 15 -> 89 -> 73 -> 85 -> 71 -> 61 -> 95 -> 5 -> 95 -> 69 -> 71 -> 37 -> 69 -> 37 -> 89 -> 55 -> 11 -> 73 -> 93 -> 45 -> 89 -> 57 -> 31 -> 31 -> 61 -> 33 -> 23 -> 59 -> 47 -> 37 -> 99 -

## Challenge 3: tables or trees?

In [36]:
import names
import numpy as np

f_names = [names.get_first_name() for i in range(1000)]
l_names = [names.get_last_name() for i in range(1000)]

fullnames = [f'{fn} {ln}' for fn in f_names for ln in l_names]
np.random.shuffle(fullnames)
ages = np.random.randint(18,75,1000000).tolist()

In [37]:
print(fullnames[:10])
print(ages[:10])

['Mary Klemm', 'Thomas Bennett', 'Richard Monro', 'Timothy Weinstein', 'Kurt Garcia', 'Lillian Bettencourt', 'James Garcia', 'David Conroy', 'Kathy Ulibarri', 'Adam Bannister']
[47, 67, 68, 24, 26, 66, 31, 65, 72, 49]


In [38]:
fullnames.append('Roy Jafari')
ages.append(35)

In [39]:
import pandas as pd

import time
t0=time.time()
person_df = pd.DataFrame(
    {'Name':fullnames, 'Age':ages}
)
print(time.time()-t0)
print(person_df)

0.3983609676361084
                       Name  Age
0                Mary Klemm   47
1            Thomas Bennett   67
2             Richard Monro   68
3         Timothy Weinstein   24
4               Kurt Garcia   26
...                     ...  ...
999996        Roberto Smith   54
999997   Josephine Arbogast   71
999998        Donna Ramirez   70
999999         Harold Laban   62
1000000          Roy Jafari   35

[1000001 rows x 2 columns]


In [40]:
person_df[person_df.Name == 'Roy Jafari']

Name  Age
1000000  Roy Jafari   35

In [41]:
t0=time.time()
person_df[person_df.Name == 'Roy Jafari']
print(time.time()-t0,'(s)')

0.1685631275177002 (s)


In [42]:
class TreeNode(object):
    def __init__(self,name=None,age=None):
        self.left = None
        self.right = None
        self.name = name
        self.age = age

In [43]:
def insert(root,new_name,new_age):
    if root is None:
        root=TreeNode(new_name,new_age)
        return root
 
    if new_name<root.name:
        root.left=insert(root.left,new_name,new_age)
    else:
        root.right=insert(root.right,new_name,new_age)
    return root

In [44]:
t0=time.time()
root = None
for name,age in zip(fullnames,ages):
    root = insert(root,name,age)
print(time.time()-t0,'(s)')

18.108522176742554 (s)


In [45]:
print('\t\t',root.left.left.name,root.left.left.age)
print('\t',root.left.name,root.left.age)
print('\t\t',root.left.right.name,root.left.right.age)
print(root.name,root.age)
print('\t\t',root.right.left.name,root.right.left.age)
print('\t',root.right.name,root.right.age)
print('\t\t',root.right.right.name,root.right.right.age)

		 James Garcia 31
	 Kurt Garcia 26
		 Lillian Bettencourt 66
Mary Klemm 47
		 Richard Monro 68
	 Thomas Bennett 67
		 Timothy Weinstein 24


In [47]:
def find(root,name):
    if root is None:
        return 'Does not Exist'
    #print(root.name)
    if root.name == name:
        return root
    
    if name<root.name:
        return find(root.left,name)
    else:
        return find(root.right,name)

In [48]:
node = find(root,'Roy Jafari')
print(node.name)
print(node.age)

Roy Jafari
35


In [49]:
t0=time.time()
find(root,'Roy Jafari')
print(time.time()-t0)

0.0


In [50]:
def find(root,name):
    if root is None:
        return 'Does not Exist'
    print(root.name)
    if root.name == name:
        return root
    
    if name<root.name:
        return find(root.left,name)
    else:
        return find(root.right,name)
find(root,'Roy Jafari')

Mary Klemm
Thomas Bennett
Richard Monro
Robert Anderson
Stephen Dumond
Roger Hildebrand
Stephen Deubler
Sara Knoll
Rosa Barone
Ruth Eddy
Roy Ackerson
Ruben Moody
Roy Kallam
Roy Jennings
Roy Fielding
Roy Hill
Roy Hudson
Roy Jackson
Roy Jackson
Roy Jarrell
Roy Jackson
Roy James
Roy Jackson
Roy Jackson
Roy Jackson
Roy Jackson
Roy Jackson
Roy Jackson
Roy Jackson
Roy Jackson
Roy Jackson
Roy Jafari


## Challenge 4: tables or graphs?

In [1]:
import pandas as pd
class GraphLE(object):
    def __init__(self,n_nodes=None):
        self.edge_df = pd.DataFrame(
            columns = ['n1','n2','w']
        )
        self.n_nodes = n_nodes
    def add_edge(self,n1,n2,w=1):
        add_df = pd.DataFrame(
            {'n1': n1, 'n2': n2, 'w': w},
            index=[len(self.edge_df)]
        )
        self.edge_df = pd.concat([self.edge_df,add_df])
    def print_all_adj_list(self):
        print(self.edge_df)
    def get_edge_from(self,node):
        BM = self.edge_df.n1 == node
        return [(r.n1,r.n2,r.w) for i,r in 
               self.edge_df[BM].iterrows()]

In [2]:
import numpy as np
import pandas as pd
class GraphAM(object):
    def __init__(self,n_nodes):
        self.n_nodes = n_nodes
        self.adj_matrix = (
            np.zeros([n_nodes,n_nodes])
            .astype(int)
        )
    def add_edge(self,n1,n2,w=1):
        self.adj_matrix[n1,n2] = w
    def print_adj_matrix(self):
        print(self.adj_matrix)
    def get_edge_from(self,n1):
        return [(n1,n2,w) for n2,w in
                enumerate(self.adj_matrix[n1,:]) if w>0]

In [3]:
class GraphAL(object):
    def __init__(self,n_nodes):
        self.n_nodes = n_nodes
        self.adj_list = {
            node: list() for node in range(self.n_nodes)
        }
    def add_edge(self,n1,n2,w=1):
        (self
         .adj_list[n1]
         .append((n2,w))
        )
    def print_all_adj_list(self):
        for key in self.adj_list.keys():
            print(key,self.adj_list[key])
    def get_edge_from(self,n1):
        return [(n1,n2,w) for n2,w in self.adj_list[n1]]

In [4]:
edge_list = [(3,0,5),(3,1,2),(1,0,7),(0,2,1),(2,5,9),(6,2,3),(5,6,3),(5,1,2),(5,4,9),(4,1,3),(4,5,8)]
n_nodes = 7
le_graph = GraphLE(n_nodes)
for n1,n2,w in edge_list:
    le_graph.add_edge(n1, n2, w)

In [5]:
le_graph.print_all_adj_list()

   n1 n2  w
0   3  0  5
1   3  1  2
2   1  0  7
3   0  2  1
4   2  5  9
5   6  2  3
6   5  6  3
7   5  1  2
8   5  4  9
9   4  1  3
10  4  5  8


In [6]:
import pandas as pd
import numpy as np

def dijkstra(graph,source):
    n_nodes = graph.n_nodes
    
    min_dist = pd.Series(float('inf'),index=range(n_nodes))
    min_dist[source] = 0
    
    finalized = pd.Series(False,index=range(n_nodes))
    final_path = {node:None for node in range(n_nodes)}
    
    while sum(finalized) <n_nodes:
        node = min_dist[finalized==False].idxmin()
        for n1,n2,w in graph.get_edge_from(node):
            
            new_w = min_dist.iloc[n1] + w 
            
            if(new_w< min_dist.iloc[n2]):
                min_dist.iloc[n2] = new_w
                final_path[n2] = n1
        
        finalized[node] = True
        
    shortest_paths = {}
    
    for i in range(n_nodes):
        path = []
        dest = i

        path.append(dest)

        while final_path[dest] != None:
            path.append(final_path[dest])
            dest = final_path[dest]
        
        shortest_paths[i] = path[::-1]

    return min_dist, shortest_paths

In [7]:
source=3
min_path, shortest_path =  dijkstra(le_graph,source)
print(min_path)
print(shortest_path)

0     5.0
1     2.0
2     6.0
3     0.0
4    24.0
5    15.0
6    18.0
dtype: float64
{0: [3, 0], 1: [3, 1], 2: [3, 0, 2], 3: [3], 4: [3, 0, 2, 5, 4], 5: [3, 0, 2, 5], 6: [3, 0, 2, 5, 6]}


In [8]:
import numpy as np

n_nodes = 10000
n_edges = 50000

edges = np.random.randint(0,n_nodes,[n_edges,2])
weights = np.random.randint(1,25,n_edges)

edge_list = [(edges[i,0],edges[i,1],weights[i]) for i in range(n_edges)]

In [9]:
datastrcutre_options = {'table': GraphLE,
                       'matrix': GraphAM,
                       'graph': GraphAL}

result_df = pd.DataFrame(
    index = datastrcutre_options,
    columns = ['FillingTime','RunTime']
)

print(result_df)

       FillingTime RunTime
table          NaN     NaN
matrix         NaN     NaN
graph          NaN     NaN


In [10]:
import time
for ds_name, ds_class in datastrcutre_options.items():
    t0 = time.time()
    graph = ds_class(n_nodes)
    for s,d,w in edge_list:
        graph.add_edge(s, d, w)
    
    result_df.at[ds_name,'FillingTime'] = time.time() - t0
    
    t0 = time.time()
    min_dist, shortest_path =  dijkstra(graph,4)
    result_df.at[ds_name,'RunTime'] = time.time() - t0
print(result_df)

       FillingTime    RunTime
table    38.918721  96.296619
matrix     0.29684   24.24543
graph     0.062488   8.355926


In [ ]:
import time 
t0 = time.time()
road_am_graph = GraphAM(n_nodes)
for s,d,w in edge_list:
    road_le_graph.add_edge(s, d, w)
print(time.time() - t0, '(s)')

In [ ]:
import time 
t0 = time.time()
road_le_graph = GraphLE(n_nodes)
for s,d,w in edge_list:
    road_le_graph.add_edge(s, d, w)
print(time.time() - t0, '(s)')

In [42]:
%%time
source = 4
min_dist, shortest_path =  dijkstra(road_le_graph,source)

Wall time: 42.7 s


In [43]:
min_dist

0      8.0
1      6.0
2      8.0
3      7.0
4      0.0
      ... 
995    9.0
996    8.0
997    6.0
998    6.0
999    8.0
Length: 1000, dtype: float64

In [44]:
shortest_path

{0: [4, 576, 165, 0],
 1: [4, 760, 860, 703, 1],
 2: [4, 931, 355, 216, 318, 511, 2],
 3: [4, 931, 355, 295, 3],
 4: [4],
 5: [4, 931, 242, 721, 5],
 6: [4, 931, 242, 230, 60, 398, 6],
 7: [4, 760, 668, 22, 454, 7],
 8: [4, 931, 355, 395, 8],
 9: [4, 931, 251, 408, 95, 9],
 10: [4, 931, 355, 504, 324, 861, 10],
 11: [4, 931, 355, 122, 11],
 12: [4, 931, 251, 649, 558, 339, 777, 12],
 13: [4, 931, 251, 649, 558, 844, 13],
 14: [4, 931, 251, 885, 534, 14],
 15: [4, 931, 355, 531, 15],
 16: [4, 931, 355, 147, 140, 282, 16],
 17: [4, 931, 251, 506, 17],
 18: [4, 576, 165, 18],
 19: [4, 931, 251, 577, 19],
 20: [4, 931, 20],
 21: [4, 931, 251, 649, 21],
 22: [4, 760, 668, 22],
 23: [4, 931, 242, 792, 23],
 24: [4, 924, 350, 362, 24],
 25: [4, 931, 251, 649, 164, 25],
 26: [4, 576, 165, 18, 26],
 27: [4, 931, 355, 122, 11, 222, 27],
 28: [4, 760, 668, 22, 454, 7, 28],
 29: [4, 760, 443, 279, 29],
 30: [4, 576, 119, 382, 902, 30],
 31: [4, 931, 251, 480, 373, 762, 31],
 32: [4, 760, 103, 634,